before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on

  goarch:
  - amd64

  goos:
  - darwin
  - linux
  - windows

archives:
- format_overrides:
  - goos: windows
    format: zip
  
  files:
    - LICENSE
    - Readme.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
